### ISSUE TITLE
Route config prefix

### ISSUE THREAD

**Issue by cepheiVV** [Mirko-Solutions/t3customroutes#1]
Setting up a route like in the example doesn't work for me.

The example config
```
api_post_show:
  path: /api/posts/{id}
  controller: App\Controller\BlogApiController::show
  methods: GET
```
will not find the rount under `/api/posts/123`, but instead looks for `/api/api/posts/123`

The `api` prefix is set in 
`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['t3customroutes']['basePath']`
But setting this config to `/` doesn't work either.

The only workaround that working for me is to skip the `/api/ ` part in the config:
```
api_post_show:
  path: /posts/{id}
  controller: App\Controller\BlogApiController::show
  methods: GET
```
